/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "mUART.h"
#include "mUART_SPI_UART.h"
#include "mUART_PINS.h"
#include "mUART_SPI_UART_PVT.h"
#include "mUART_PVT.h"
#include "mUART_BOOT.h"
#include "mBootloadable.h"
#include "mPWM0.h"
#include "LEDR.h"
#include "LEDR_aliases.h"
#include "C12M.h"
#include "mPWM1.h"
#include "LEDG.h"
#include "LEDG_aliases.h"
#include "mPWM2.h"
#include "LEDB.h"
#include "LEDB_aliases.h"
#include "mUART_SCBCLK.h"
#include "mUART_tx.h"
#include "mUART_tx_aliases.h"
#include "mUART_rx.h"
#include "mUART_rx_aliases.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

